#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseDeDatos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="NuevaBase")]
	public partial class DataClassDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void Insertliquidacion(liquidacion instance);
    partial void Updateliquidacion(liquidacion instance);
    partial void Deleteliquidacion(liquidacion instance);
    partial void Insertpesa(pesa instance);
    partial void Updatepesa(pesa instance);
    partial void Deletepesa(pesa instance);
    partial void InsertpesaCalculada(pesaCalculada instance);
    partial void UpdatepesaCalculada(pesaCalculada instance);
    partial void DeletepesaCalculada(pesaCalculada instance);
    #endregion
		
		public DataClassDataContext() : 
				base(global::BaseDeDatos.Properties.Settings.Default.NuevaBaseConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<liquidacion> liquidacion
		{
			get
			{
				return this.GetTable<liquidacion>();
			}
		}
		
		public System.Data.Linq.Table<pesa> pesa
		{
			get
			{
				return this.GetTable<pesa>();
			}
		}
		
		public System.Data.Linq.Table<pesaCalculada> pesaCalculada
		{
			get
			{
				return this.GetTable<pesaCalculada>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.liquidacion")]
	public partial class liquidacion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _embarcacion;
		
		private string _detalle;
		
		private string _procedencia;
		
		private string _monto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnembarcacionChanging(string value);
    partial void OnembarcacionChanged();
    partial void OndetalleChanging(string value);
    partial void OndetalleChanged();
    partial void OnprocedenciaChanging(string value);
    partial void OnprocedenciaChanged();
    partial void OnmontoChanging(string value);
    partial void OnmontoChanged();
    #endregion
		
		public liquidacion()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_embarcacion", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string embarcacion
		{
			get
			{
				return this._embarcacion;
			}
			set
			{
				if ((this._embarcacion != value))
				{
					this.OnembarcacionChanging(value);
					this.SendPropertyChanging();
					this._embarcacion = value;
					this.SendPropertyChanged("embarcacion");
					this.OnembarcacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_detalle", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string detalle
		{
			get
			{
				return this._detalle;
			}
			set
			{
				if ((this._detalle != value))
				{
					this.OndetalleChanging(value);
					this.SendPropertyChanging();
					this._detalle = value;
					this.SendPropertyChanged("detalle");
					this.OndetalleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_procedencia", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string procedencia
		{
			get
			{
				return this._procedencia;
			}
			set
			{
				if ((this._procedencia != value))
				{
					this.OnprocedenciaChanging(value);
					this.SendPropertyChanging();
					this._procedencia = value;
					this.SendPropertyChanged("procedencia");
					this.OnprocedenciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_monto", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string monto
		{
			get
			{
				return this._monto;
			}
			set
			{
				if ((this._monto != value))
				{
					this.OnmontoChanging(value);
					this.SendPropertyChanging();
					this._monto = value;
					this.SendPropertyChanged("monto");
					this.OnmontoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.pesa")]
	public partial class pesa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _embarcacion;
		
		private string _tipoPescado;
		
		private string _pesa1;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnembarcacionChanging(string value);
    partial void OnembarcacionChanged();
    partial void OntipoPescadoChanging(string value);
    partial void OntipoPescadoChanged();
    partial void Onpesa1Changing(string value);
    partial void Onpesa1Changed();
    #endregion
		
		public pesa()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_embarcacion", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string embarcacion
		{
			get
			{
				return this._embarcacion;
			}
			set
			{
				if ((this._embarcacion != value))
				{
					this.OnembarcacionChanging(value);
					this.SendPropertyChanging();
					this._embarcacion = value;
					this.SendPropertyChanged("embarcacion");
					this.OnembarcacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipoPescado", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string tipoPescado
		{
			get
			{
				return this._tipoPescado;
			}
			set
			{
				if ((this._tipoPescado != value))
				{
					this.OntipoPescadoChanging(value);
					this.SendPropertyChanging();
					this._tipoPescado = value;
					this.SendPropertyChanged("tipoPescado");
					this.OntipoPescadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="pesa", Storage="_pesa1", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string pesa1
		{
			get
			{
				return this._pesa1;
			}
			set
			{
				if ((this._pesa1 != value))
				{
					this.Onpesa1Changing(value);
					this.SendPropertyChanging();
					this._pesa1 = value;
					this.SendPropertyChanged("pesa1");
					this.Onpesa1Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.pesaCalculada")]
	public partial class pesaCalculada : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _embarcacion;
		
		private string _fecha;
		
		private string _tipoPescado;
		
		private string _ToatlPesa;
		
		private string _montoTotalPesa;
		
		private string _precio;
		
		private int _id;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnembarcacionChanging(string value);
    partial void OnembarcacionChanged();
    partial void OnfechaChanging(string value);
    partial void OnfechaChanged();
    partial void OntipoPescadoChanging(string value);
    partial void OntipoPescadoChanged();
    partial void OnToatlPesaChanging(string value);
    partial void OnToatlPesaChanged();
    partial void OnmontoTotalPesaChanging(string value);
    partial void OnmontoTotalPesaChanged();
    partial void OnprecioChanging(string value);
    partial void OnprecioChanged();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    #endregion
		
		public pesaCalculada()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_embarcacion", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string embarcacion
		{
			get
			{
				return this._embarcacion;
			}
			set
			{
				if ((this._embarcacion != value))
				{
					this.OnembarcacionChanging(value);
					this.SendPropertyChanging();
					this._embarcacion = value;
					this.SendPropertyChanged("embarcacion");
					this.OnembarcacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this.OnfechaChanging(value);
					this.SendPropertyChanging();
					this._fecha = value;
					this.SendPropertyChanged("fecha");
					this.OnfechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipoPescado", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string tipoPescado
		{
			get
			{
				return this._tipoPescado;
			}
			set
			{
				if ((this._tipoPescado != value))
				{
					this.OntipoPescadoChanging(value);
					this.SendPropertyChanging();
					this._tipoPescado = value;
					this.SendPropertyChanged("tipoPescado");
					this.OntipoPescadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ToatlPesa", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string ToatlPesa
		{
			get
			{
				return this._ToatlPesa;
			}
			set
			{
				if ((this._ToatlPesa != value))
				{
					this.OnToatlPesaChanging(value);
					this.SendPropertyChanging();
					this._ToatlPesa = value;
					this.SendPropertyChanged("ToatlPesa");
					this.OnToatlPesaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_montoTotalPesa", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string montoTotalPesa
		{
			get
			{
				return this._montoTotalPesa;
			}
			set
			{
				if ((this._montoTotalPesa != value))
				{
					this.OnmontoTotalPesaChanging(value);
					this.SendPropertyChanging();
					this._montoTotalPesa = value;
					this.SendPropertyChanged("montoTotalPesa");
					this.OnmontoTotalPesaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string precio
		{
			get
			{
				return this._precio;
			}
			set
			{
				if ((this._precio != value))
				{
					this.OnprecioChanging(value);
					this.SendPropertyChanging();
					this._precio = value;
					this.SendPropertyChanged("precio");
					this.OnprecioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
